/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @author mweeg
 */
public class TelaGestaodeContato extends javax.swing.JDialog {

    //atributos
    private static final int VISUALIZACAO = 1;
    private static final int EDICAO = 2;
    private static final int INSERCAO = 3;
    private int estado;
    private int totCarregado;
    private int corrente = -1;
    private Agenda agenda;

    public TelaGestaodeContato(java.awt.Frame parent, boolean modal, Agenda agenda) {
        super(parent, modal);
        initComponents();
        this.agenda = agenda;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDadosContato = new javax.swing.JPanel();
        jLNome = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jFTFTelefone = new javax.swing.JFormattedTextField();
        jPBarraOperacoes = new javax.swing.JPanel();
        jBPrimeiro = new javax.swing.JButton();
        jBAnterior = new javax.swing.JButton();
        jBProximo = new javax.swing.JButton();
        jBUltimo = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jBEdita = new javax.swing.JButton();
        jBGrava = new javax.swing.JButton();
        jBExclui = new javax.swing.JButton();
        jBDesfaz = new javax.swing.JButton();
        jBEncerraCadastro = new javax.swing.JButton();

        setTitle("Gestão de Contatos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPDadosContato.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestao de Contatos"));

        jLNome.setText("Nome:");

        jLTelefone.setText("Telefone:");

        jLEmail.setText("E-mail:");

        javax.swing.GroupLayout jPDadosContatoLayout = new javax.swing.GroupLayout(jPDadosContato);
        jPDadosContato.setLayout(jPDadosContatoLayout);
        jPDadosContatoLayout.setHorizontalGroup(
            jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLEmail)
                    .addComponent(jLNome)
                    .addComponent(jLTelefone))
                .addGap(18, 18, 18)
                .addGroup(jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPDadosContatoLayout.setVerticalGroup(
            jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosContatoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefone)
                    .addComponent(jFTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmail)
                    .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jBPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/Rewind16.gif"))); // NOI18N
        jBPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrimeiroActionPerformed(evt);
            }
        });

        jBAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/Back16.gif"))); // NOI18N
        jBAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnteriorActionPerformed(evt);
            }
        });

        jBProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/Forward16.gif"))); // NOI18N
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });

        jBUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/FastForward16.gif"))); // NOI18N
        jBUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoActionPerformed(evt);
            }
        });

        jBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/New16.gif"))); // NOI18N
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jBEdita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/gtk-edit.png"))); // NOI18N
        jBEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditaActionPerformed(evt);
            }
        });

        jBGrava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/Save16.gif"))); // NOI18N
        jBGrava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravaActionPerformed(evt);
            }
        });

        jBExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/Delete16.gif"))); // NOI18N
        jBExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluiActionPerformed(evt);
            }
        });

        jBDesfaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/undo.png"))); // NOI18N
        jBDesfaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDesfazActionPerformed(evt);
            }
        });

        jBEncerraCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/delete_edit.gif"))); // NOI18N
        jBEncerraCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEncerraCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBarraOperacoesLayout = new javax.swing.GroupLayout(jPBarraOperacoes);
        jPBarraOperacoes.setLayout(jPBarraOperacoesLayout);
        jPBarraOperacoesLayout.setHorizontalGroup(
            jPBarraOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEdita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGrava, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDesfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEncerraCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPBarraOperacoesLayout.setVerticalGroup(
            jPBarraOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBarraOperacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBarraOperacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBNovo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEdita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGrava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBExclui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDesfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEncerraCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDadosContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPBarraOperacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDadosContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPBarraOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEncerraCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEncerraCadastroActionPerformed
       finaliza();
    }//GEN-LAST:event_jBEncerraCadastroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        load();
        setEstado(1);
        exibeDados();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        finaliza();
    }//GEN-LAST:event_formWindowClosing

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        limpaCampos(jPDadosContato);
        setEstado(3);

    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBGravaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravaActionPerformed
        String simNao[] = {"Sim", "Nao"};
        if (jTFNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo nome", "Aviso", 0);
            jTFNome.setText("");
            jTFNome.requestFocusInWindow();
            return;
        }
        int salva = JOptionPane.showOptionDialog(null, "Confirma os dados?",
                "Gravando...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, simNao, simNao[0]);
        if (salva == 0) {
            Contato contato = montaContato();
            
            if (estado == 3) {
                if (agenda.adicionaContatos(contato)) {
                    JOptionPane.showMessageDialog(null, "Novo registro armazenado com sucesso!",
                            "Cadastro de Contato", JOptionPane.INFORMATION_MESSAGE);
                    load();
                    corrente = agenda.posContato(contato);
                } else {
                    JOptionPane.showMessageDialog(null, "Operação cancelada!Já existe um contato com este nome",
                            "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
                }
                
                
            } else if (estado == 2) {
                if (agenda.alteraContatos(contato)) {
                    JOptionPane.showMessageDialog(null, "Alteracao realizada com sucesso!!!", "Cadastro de Contato",
                            JOptionPane.INFORMATION_MESSAGE);
                    load();
                    corrente = agenda.posContato(contato);
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Contato não localizado", "Cadastro de Contato",
                            JOptionPane.ERROR_MESSAGE);
                    
                }
            }
            setEstado(1);
            exibeDados();
        }

    }//GEN-LAST:event_jBGravaActionPerformed

    private void jBPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrimeiroActionPerformed
                if (agenda.primeiro() == -1) {
            JOptionPane.showMessageDialog(this, "Nao ha registro",
                    "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
        } else {
            corrente = agenda.primeiro();
        }
        exibeDados();
    }//GEN-LAST:event_jBPrimeiroActionPerformed

    private void jBUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoActionPerformed
                if (agenda.ultimo() == -1) {
            JOptionPane.showMessageDialog(this, "Nao ha registro",
                    "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
        } else {
            corrente = agenda.ultimo();
        }
        exibeDados();

    }//GEN-LAST:event_jBUltimoActionPerformed

    private void jBAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnteriorActionPerformed
        if (corrente == -1) {
            JOptionPane.showMessageDialog(this, "Nao ha registro",
                    "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
        } else if (corrente >= 1) {
            corrente -= 1;
        } else {
            JOptionPane.showMessageDialog(this, "Primeiro registro",
                    "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
        }
        exibeDados();

    }//GEN-LAST:event_jBAnteriorActionPerformed

    private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
        if (corrente == -1) {
            JOptionPane.showMessageDialog(this, "Nao ha registro",
                    "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
        } else if (corrente < totCarregado - 1) {
            corrente += 1;
        } else {
            JOptionPane.showMessageDialog(this, "ultimo registro",
                    "Cadastro de Contato", JOptionPane.ERROR_MESSAGE);
        }
        exibeDados();

    }//GEN-LAST:event_jBProximoActionPerformed

    private void jBDesfazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDesfazActionPerformed
        setEstado(1);
        exibeDados();

    }//GEN-LAST:event_jBDesfazActionPerformed

    private void jBExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluiActionPerformed
        String simNao[] = {"Sim", "Nao"};
        int exclui = JOptionPane.showOptionDialog(null,
                "Confirma exclusao?",
                "Excluindo...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, simNao, simNao[1]);
        if (exclui == 0) {
            Contato contatoExcluido = montaContato();
            int regDeletado = corrente;
            if (agenda.removeContato(contatoExcluido)) {
                JOptionPane.showMessageDialog(null, "Operacao de exclusao realizada com sucesso!!!",
                        "Cadastro de Contato",
                        JOptionPane.INFORMATION_MESSAGE);
                
                load();
                if (regDeletado < totCarregado) {
                    corrente = regDeletado;
                } else {
                    corrente = totCarregado - 1;
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Contato não localizado", "Cadastro de Contato - operacao Excluir",
                        JOptionPane.ERROR_MESSAGE);
            }
            setEstado(1);
            exibeDados();
        }

    }//GEN-LAST:event_jBExcluiActionPerformed

    private void jBEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditaActionPerformed
        setEstado(2);
    }//GEN-LAST:event_jBEditaActionPerformed

    private Contato montaContato() {
   
        Contato contato = new Contato();
        contato.setNome(jTFNome.getText());
        contato.setTelefone(jFTFTelefone.getText());
        contato.setEmail(jTFEmail.getText());
        
        return contato;
    }
    
    public int getEstado() {
        return estado;
    }
    
    private void load() {
        //jTFNome.setText(String.valueOf(agenda.getTotContatos()));
        totCarregado = agenda.getTotContatos();
        if (totCarregado > 0) {
            corrente = 0;
        }
    }
    private void exibeDados() {
        limpaCampos(jPDadosContato);
        if (corrente != -1) {
            jTFNome.setText(agenda.getContato(corrente).getNome());
            jFTFTelefone.setText(agenda.getContato(corrente).getTelefone());
            jTFEmail.setText(agenda.getContato(corrente).getEmail());
        }
        
    }
public void limpaCampos(javax.swing.JPanel jpanel) {
        java.awt.Component[] componentes = jpanel.getComponents();
        javax.swing.JTextField textField = null;
        
        for (int i = 0; i < componentes.length; i++) {
            // System.out.println("COMPONENTE "+componentes[i].getClass().getName() );
            if (componentes[i] instanceof javax.swing.JTextField) {
                textField = (javax.swing.JTextField) componentes[i];
                textField.setText("");
            }
        }
    }
public void setEstado(int estado) {
        this.estado = estado;
        if (estado == VISUALIZACAO) {
            jTFNome.setEditable(false);
            jFTFTelefone.setEditable(false);
            jTFEmail.setEditable(false);
            jBPrimeiro.setEnabled(totCarregado != 0);
            jBUltimo.setEnabled(totCarregado != 0);
            jBProximo.setEnabled(totCarregado != 0);
            jBAnterior.setEnabled(totCarregado != 0);
            jBNovo.setEnabled(true);
            jBEdita.setEnabled(totCarregado != 0);
            jBGrava.setEnabled(false);
            jBExclui.setEnabled(totCarregado != 0);
            jBEncerraCadastro.setEnabled(true);
            jBDesfaz.setEnabled(false);
        } else if (estado == INSERCAO) {
            jTFNome.setEditable(true);
            jFTFTelefone.setEditable(true);
            jTFEmail.setEditable(true);
            jBPrimeiro.setEnabled(false);
            jBUltimo.setEnabled(false);
            jBProximo.setEnabled(false);
            jBAnterior.setEnabled(false);
            jBNovo.setEnabled(false);
            jBEdita.setEnabled(false);
            jBGrava.setEnabled(true);
            jBExclui.setEnabled(false);
            jBDesfaz.setEnabled(true);
            jBEncerraCadastro.setEnabled(true);
            jTFNome.requestFocus();
        } else {
            if (estado == EDICAO) {
                jTFNome.setEditable(false);
                jFTFTelefone.setEditable(true);
                jTFEmail.setEditable(true);
                jBPrimeiro.setEnabled(false);
                jBUltimo.setEnabled(false);
                jBProximo.setEnabled(false);
                jBAnterior.setEnabled(false);
                jBNovo.setEnabled(false);
                jBEdita.setEnabled(false);
                jBGrava.setEnabled(true);
                jBExclui.setEnabled(false);
                jBDesfaz.setEnabled(true);
                jBEncerraCadastro.setEnabled(true);
                jFTFTelefone.requestFocus();
            }
        }
    }
    
    private void finaliza() {
       dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGestaodeContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGestaodeContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGestaodeContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGestaodeContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnterior;
    private javax.swing.JButton jBDesfaz;
    private javax.swing.JButton jBEdita;
    private javax.swing.JButton jBEncerraCadastro;
    private javax.swing.JButton jBExclui;
    private javax.swing.JButton jBGrava;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPrimeiro;
    private javax.swing.JButton jBProximo;
    private javax.swing.JButton jBUltimo;
    private javax.swing.JFormattedTextField jFTFTelefone;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JPanel jPBarraOperacoes;
    private javax.swing.JPanel jPDadosContato;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
