/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @author mweeg
 */
public class TelaAgendaEletronicaArray extends javax.swing.JFrame {


    /**
     * Creates new form TelaAgendaEletronicaArray
     */
    private Agenda agenda = new Agenda();
    public TelaAgendaEletronicaArray() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMBPrincipal = new javax.swing.JMenuBar();
        jMCadastro = new javax.swing.JMenu();
        jMICadContato = new javax.swing.JMenuItem();
        jMLista = new javax.swing.JMenu();
        jMIContatos = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMISobre = new javax.swing.JMenuItem();
        jMOpcoes = new javax.swing.JMenu();
        jMISair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda Eletronica");

        jMCadastro.setText("Cadastrar");

        jMICadContato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMICadContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/Profile.png"))); // NOI18N
        jMICadContato.setText("Contato");
        jMICadContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadContatoActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICadContato);

        jMBPrincipal.add(jMCadastro);

        jMLista.setText("Listar");

        jMIContatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMIContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/History16.gif"))); // NOI18N
        jMIContatos.setText("Contatos");
        jMIContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIContatosActionPerformed(evt);
            }
        });
        jMLista.add(jMIContatos);

        jMBPrincipal.add(jMLista);

        jMAjuda.setText("Ajuda");

        jMISobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMISobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/contato.gif"))); // NOI18N
        jMISobre.setText("Sobre");
        jMISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISobreActionPerformed(evt);
            }
        });
        jMAjuda.add(jMISobre);

        jMBPrincipal.add(jMAjuda);

        jMOpcoes.setText("Opções");

        jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMISair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/imgs/close_view.gif"))); // NOI18N
        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMOpcoes.add(jMISair);

        jMBPrincipal.add(jMOpcoes);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMICadContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadContatoActionPerformed
        TelaGestaodeContato dialog = new TelaGestaodeContato(this, true, agenda);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMICadContatoActionPerformed

    private void jMIContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIContatosActionPerformed
        TelaPesquisa pesquisa = new TelaPesquisa(this, true, agenda);
        pesquisa.setVisible(true);
    }//GEN-LAST:event_jMIContatosActionPerformed

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(-1);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
         JOptionPane.showMessageDialog(this, "Software - Agenda Eletrônica. V1.0"
                 + "Autor: Magno Weege de Oliveira",
                    "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMISobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaEletronicaArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaEletronicaArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaEletronicaArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAgendaEletronicaArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAgendaEletronicaArray().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenu jMCadastro;
    private javax.swing.JMenuItem jMICadContato;
    private javax.swing.JMenuItem jMIContatos;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenu jMLista;
    private javax.swing.JMenu jMOpcoes;
    // End of variables declaration//GEN-END:variables
}
